CREATE TABLE `clients` (
  `clientID` int(11) NOT NULL AUTO_INCREMENT,
  `search_help` varchar(255) NOT NULL DEFAULT '',
  `Client_Type` varchar(20) NOT NULL DEFAULT '',
  `Client_Name` varchar(100) NOT NULL DEFAULT 'client',
  `display_name` varchar(255) DEFAULT NULL,
  `aspect` varchar(255) DEFAULT NULL,
  `Broker` int(11) DEFAULT NULL,
  `Client_Phone` varchar(40) DEFAULT '',
  `Website` varchar(100) DEFAULT '',
  `Client_Since` date NOT NULL DEFAULT '0000-00-00',
  `tempID` varchar(50) DEFAULT '',
  `Client_Status` int(11) DEFAULT '1',
  `enhanced_password` int(11) DEFAULT '0',
  `client_hours` varchar(255) DEFAULT '2',
  `issuesBroker` int(11) DEFAULT NULL,
  `issuesClient` int(11) DEFAULT NULL,
  `issue_frequency` int(11) DEFAULT '1',
  `industry` varchar(255) DEFAULT NULL,
  `companySize` varchar(255) DEFAULT NULL,
  `actualCompanySize` int(11) DEFAULT NULL,
  `companyType` varchar(30) DEFAULT NULL,
  `salesNotes` mediumtext,
  `customClient` int(11) DEFAULT '0',
  `groupID` varchar(60) DEFAULT '',
  `deactivationDate` date DEFAULT NULL,
  `deactivationID` int(11) DEFAULT NULL,
  `login` int(11) DEFAULT '0',
  `producer` varchar(200) DEFAULT NULL,
  `specialDomain` varchar(255) DEFAULT NULL,
  `addedBy` varchar(50) DEFAULT NULL,
  `channel` varchar(255) DEFAULT NULL,
  `directID` int(11) DEFAULT NULL,
  `resellerID` int(11) DEFAULT NULL,
  `parentID` int(11) DEFAULT NULL,
  `familiesID` int(11) DEFAULT NULL,
  `referral` varchar(50) DEFAULT NULL,
  `tally` int(11) DEFAULT '0',
  `optOut` int(11) DEFAULT '0',
  `optOutWelcome` int(1) DEFAULT '0',
  `newsletterID` int(11) DEFAULT '0',
  `newsletterPrivateLabel` int(1) DEFAULT '0',
  `officeLocation` varchar(50) DEFAULT NULL,
  `partnerClientType` varchar(50) DEFAULT NULL,
  `marketID` int(11) DEFAULT NULL,
  `marketCode` varchar(70) DEFAULT NULL,
  `suspended` datetime DEFAULT NULL,
  `marketingCampaign` varchar(120) DEFAULT NULL,
  `marketingFree` int(5) DEFAULT NULL,
  `avoidTerms` int(11) DEFAULT '0',
  `custom1` varchar(255) DEFAULT NULL,
  `custom2` varchar(255) DEFAULT NULL,
  `custom3` varchar(255) DEFAULT NULL,
  `custom4` varchar(255) DEFAULT NULL,
  `custom5` varchar(255) DEFAULT NULL,
  `customDate` datetime DEFAULT NULL,
  `noReporting` int(11) DEFAULT '0',
  `noTerms` int(1) DEFAULT '0',
  `expiryDate` date DEFAULT NULL,
  `partnerAdmin` int(1) DEFAULT '0',
  `level` int(11) DEFAULT NULL,
  `brainID` varchar(25) DEFAULT NULL,
  `tokenID` varchar(25) DEFAULT NULL,
  `subscriptionID` varchar(30) DEFAULT NULL,
  `posters` int(1) DEFAULT '0',
  `complyLinks` int(11) DEFAULT '1',
  `resources` int(11) DEFAULT '1',
  `newLook` int(11) DEFAULT '1',
  `customStyle` int(11) DEFAULT '0',
  `setup_fee` int(11) DEFAULT NULL,
  `customerSuccessManager` int(11) DEFAULT NULL,
  `trial` int(11) DEFAULT NULL,
  `upsellLearn` int(11) DEFAULT '0',
  `sales_rep` varchar(60) DEFAULT NULL,
  `exported` int(11) DEFAULT '0',
  `direct_landing` int(11) DEFAULT NULL,
  `revenue` varchar(255) DEFAULT NULL,
  `workplaceUsers` int(11) DEFAULT NULL,
  `temp_Client_Status` int(11) DEFAULT NULL,
  `Renewal_Date` date DEFAULT NULL,
  `re_manager` int(11) DEFAULT NULL,
  `partner_manager` int(11) DEFAULT NULL,
  `auto_welcome_email` int(11) DEFAULT '1',
  `contact_assignments` int(11) DEFAULT '0',
  `salesforceID` varchar(50) DEFAULT NULL,
  `special_note` longtext NOT NULL,
  `sourceID` int(11) DEFAULT '0',
  PRIMARY KEY (`clientID`),
  KEY `Client_Type` (`Client_Type`),
  KEY `Client_Since` (`Client_Since`),
  KEY `Client_Name` (`Client_Name`),
  KEY `Client_Phone` (`Client_Phone`),
  KEY `Client_Status` (`Client_Status`),
  KEY `search_help` (`search_help`),
  KEY `Website` (`Website`),
  KEY `groupID` (`groupID`),
  KEY `Broker` (`Broker`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8